### ISSUE TITLE
why this and not `python3.8*`?

### ISSUE THREAD

**Issue by cjdcordeiro** [cjdcordeiro/pebble-to-rock-workshop#2]
https://github.com/cjdcordeiro/pebble-to-rock-workshop/blob/e36c77337b0f9379e5618746f7084cbb2f5e7821/B.How_to_build_a_rock/rockcraft.yaml#L24

Are are you installing this package in particular and not the standard python3.8 package?

**Comment by rebornplusplus** [comment]
No particular reason. Let me change it to `python3.8-venv` since it is in `focal-security` and has a later version than the current one.

**Comment by cjdcordeiro** [comment]
I meant, why is it python3.8-**venv**? why the `venv`?
